import type { Metadata } from "next";
import Link from "next/link";
import { absoluteUrl, siteName } from "@/lib/site";

const faqs = [
  {
    question: "What is oeeco?",
    answer:
      "oeeco is a gallery for AI-made web works: browser games, useful tools, visual experiments, interactive pages, and small software artifacts created with AI-assisted workflows.",
  },
  {
    question: "What counts as an AI-made web work?",
    answer:
      "A work can be AI-assisted without being fully generated by AI. The important part is that the final result is a real browser page people can open, use, play, inspect, or learn from.",
  },
  {
    question: "Can creators submit their own projects?",
    answer:
      "Yes. Creators can submit browser-based works through the submission page. A good submission has a working demo URL, clear title, honest summary, useful tags, and creator context.",
  },
  {
    question: "Are submissions reviewed before publication?",
    answer:
      "Submissions may be reviewed for availability, safety, metadata clarity, and basic substance before they appear publicly. Broken, misleading, unsafe, or spammy links may be rejected or hidden.",
  },
  {
    question: "Does oeeco host uploaded code files?",
    answer:
      "At this stage, oeeco focuses on listings and playable URLs rather than hosting arbitrary code uploads. Future upload or sandbox features would need careful security design.",
  },
  {
    question: "Why does oeeco publish a blog?",
    answer:
      "The blog explains AI-made web works, creator workflows, review standards, publishing checklists, and examples. It gives visitors context and helps creators prepare stronger submissions.",
  },
  {
    question: "How does oeeco think about AI-assisted content?",
    answer:
      "oeeco may use AI-assisted workflows to draft, structure, edit, or review content, but published pages should serve the site's specific audience with useful context and original framing.",
  },
  {
    question: "How are ads handled on oeeco?",
    answer:
      "Advertising should not interfere with core interactions, imitate navigation, or pressure visitors into accidental clicks. Game and tool controls should remain clear and usable.",
  },
  {
    question: "How can someone report a problem?",
    answer:
      "Visitors and creators can use the contact page to report broken links, unsafe behavior, misleading listings, attribution concerns, or other site issues.",
  },
];

export const metadata: Metadata = {
  title: "FAQ",
  description:
    "Frequently asked questions about oeeco, AI-made web works, submissions, review, blog content, safety, and advertising.",
  alternates: {
    canonical: "/faq",
  },
};

export default function FAQPage() {
  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    url: absoluteUrl("/faq"),
    mainEntity: faqs.map((item) => ({
      "@type": "Question",
      name: item.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.answer,
      },
    })),
  };

  return (
    <article className="info-page surface">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd).replace(/</g, "\\u003c") }}
      />

      <span className="section-kicker">FAQ</span>
      <h1 className="page-title">Frequently asked questions</h1>
      <p>
        Short answers about {siteName}, AI-made web works, creator submissions, review, publishing standards, and site
        trust signals.
      </p>

      <section className="info-section">
        <h2>About the platform</h2>
        <div className="faq-list">
          {faqs.slice(0, 3).map((item) => (
            <section key={item.question}>
              <h3>{item.question}</h3>
              <p>{item.answer}</p>
            </section>
          ))}
        </div>
      </section>

      <section className="info-section">
        <h2>Submission and review</h2>
        <div className="faq-list">
          {faqs.slice(3, 6).map((item) => (
            <section key={item.question}>
              <h3>{item.question}</h3>
              <p>{item.answer}</p>
            </section>
          ))}
        </div>
      </section>

      <section className="info-section">
        <h2>Trust, ads, and reporting</h2>
        <div className="faq-list">
          {faqs.slice(6).map((item) => (
            <section key={item.question}>
              <h3>{item.question}</h3>
              <p>{item.answer}</p>
            </section>
          ))}
        </div>
      </section>

      <div className="info-actions">
        <Link className="solid-button" href="/upload">
          Submit Work
        </Link>
        <Link className="ghost-button" href="/guidelines">
          Submission Guidelines
        </Link>
        <Link className="ghost-button" href="/contact">
          Contact
        </Link>
      </div>
    </article>
  );
}
